# Praktikumsvorbereitung - Python und Numpy

In der Sprache Python werden Sie im Praktikum programmieren, und werden dabei häufig auf die Bibliothek Numpy zurückgreifen. Aufgabe dieser Übung ist es, Sie gezielt auf bestimmte Aspekte der Programmiersprache Python und der Bibliothek Numpy hinzuweisen und etwaige Wissenslücken aufzudecken. 

**Wenn Sie Python noch nicht kennen:**

Fokussieren Sie sich auf **Datentypen** (Lists, Dictionaries, Tuples) und **Kontrollstrukturen** (For-Schleifen) sowie auf **List-Comprehensions**:

1. Absolvieren Sie bitte den kostenlosen Kurs [Introduction to Python](https://www.datacamp.com/courses/intro-to-python-for-data-science) der Lernplattform Datacamp. Dieser Kurs dauert etwa 4 Stunden und führt Sie an die wichtigsten Grundkonzepte von Python und Numpy heran.

   - Wenn Sie Bücher statt interaktive Kurse bevorzugen, empfehle ich Ihnen das Buch "Schnellstart Python", welches Sie im Netz der FH Aachen [als PDF herunterladen](https://link.springer.com/book/10.1007%2F978-3-658-26133-7) können.

2. Schauen Sie in die "Lerngruppe Python", die im ILIAS-Kurs dieser Veranstaltung verlinkt ist und wo ich Ihnen weitere Lernressourcen aufliste. Ich lade Sie herzlich ein, weitere dort genannte Kurse zu belegen.

3. Fahren Sie anschließend mit den eigentlichen Aufgaben dieser Übung weiter unten fort.

**Wenn Sie Python schon kennen:**

- Fahren Sie direkt mit den eigentlichen Aufgaben dieser Übung weiter unten fort.


## Übungsaufgaben

Numpy ist eine Python-Bibliothek, die eine effiziente Ausführung von mathematischen Operationen erlaubt. Sie werden im weiteren Verlauf der Veranstaltung Numpy dafür einsetzen, um Matrix-Vektor-Operationen, die Sie z.B. aus der linearen Algebra kennen, umzusetzen. Dazu müssen Sie sich mit sogenannten Numpy-Arrays vertraut machen.

## 1 Shapes und Co.

Das Verständnis von *Shapes* solcher Arrays ist eine wichtige Voraussetzung für eine produktive Arbeit mit diesen Datenstrukturen.

Lesen Sie [diesen Buchabschnitt](https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html) durch, um mit wichtigen Eigenschaften von Numpy Arrays vertraut zu werden. Bearbeiten Sie dann die nachfolgenden Aufgaben.

**Ihre Aufgaben**

(1) Betrachten Sie den untenstehenden Code. Beantworten Sie: Welchen [Shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) hat das Numpy Array `a`? (Dies ist wichtig: Sie werden mit dem Shape-Befehl oft arbeiten.)
a.shape = (4,)

In [2]:
import numpy as np
a = np.array([5, 10, 15, 20])
print(a.shape)
print(a.T)

(4,)
[ 5 10 15 20]


(2) Lässt sich das Array `a` als (mathematischen) Vektor interpretieren? Wenn `a` ein Vektor ist, können Sie ihn [transponieren](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html)?
1. Nein, da es sich um ein eindimensionales Array handelt.
2. Nein, da a.T = a. Eindimensionale Arrays kann man nicht transponieren.

**Hinweis ([rot13](http://www.rot13.de)-kodiert):** Fvr xöaara qnf Neenl n avpug genafcbavrera, jrvy rf ahe rvar Qvzrafvba orfvgmg: Rf ung qra Funcr (4,). Vuz sruyg rvar mjrvgr Qvzrafvba, hz nyf Fcnygra- omj. Mrvyrairxgbe vagrecergvreg jreqra mh xöaara. Cebovrera Fvr rf nhf: n.G.funcr vfg qnffryor jvr n.funcr.

(3) Betrachten Sie das unten stehende Array `b`. Erzeugen Sie aus `b` bitte zwei neue Arrays `c` und `d`: `c` soll ein Spaltenvektor sein, und `d` soll ein Zeilenvektor sein. Wie gehen Sie vor?

In [3]:
b = np.array([2, 4, 6, 8, 10])
print(b.shape)

print("Zeilenvektor")
print("1.Lösung: reshape")
x = b.reshape((1,5))
print(x)
print(x.shape)

print("2. Lösung: newaxis")
d = b[np.newaxis, :]
print(d)
print(d.shape)

print("Spaltenvektor")
print("Lösung: newaxis")
c = b[:, np.newaxis]
print(c)
print(c.shape)

(5,)
Zeilenvektor
1.Lösung: reshape
[[ 2  4  6  8 10]]
(1, 5)
2. Lösung: newaxis
[[ 2  4  6  8 10]]
(1, 5)
Spaltenvektor
Lösung: newaxis
[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]
(5, 1)


**Hinweis (rot13-kodiert):** Rf tvog irefpuvrqrar Jrtr, hz qvrf mh reervpura. Rva ordhrzre Jrt vfg qvr Neorvg zvg ac.arjnkvf. Qnmh svaqra Fvr hagre sbytraqrz Yvax zrue: uggcf://qbpf.fpvcl.bet/qbp/ahzcl/ersrerapr/pbafgnagf.ugzy#ahzcl.arjnkvf

Lässt sich `c` bzw. `d` transponieren? Warum?
Ja, weil es sich bei beidem um zweidimensionale Vektoren handelt.

(4) Betrachten Sie die dritte Zeile des unten stehenden Codes: Hat sich durch die Zeile `k[0, 1] = 10` das Array `m` geändert? Falls ja, warum? Falls nein, warum hat es sich nicht geändert?
Ja, weil beim Slicing (Basic Indexing) nur Views entstehen und keine Kopien. Daher wird beim ändern von k(0,1) auch m(0,1) geändert, weil m(0,1) auf k(0,1) zeigt.

In [4]:
k = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m = k[:2, 1:3]
print(m)
k[0, 1] = 10
print(m)

[[2 3]
 [6 7]]
[[10  3]
 [ 6  7]]


**Antwort (rot-13 kodiert):** Wn, qnf Neenl z ung fvpu träaqreg: z vfg ahe rva "Ivrj" nhs rvara Orervpu qrf Neenlf x. Rvar Äaqrehat iba x ireäaqreg qnzvg nhpu z. Ivrjf jreqra qhepu "Onfvp Fyvpvat" remrhtg. Fvr xöaara qvrf rvazny xbagebyyvrera, vaqrz Fvr zvg `cevag(z)` ibe qre qevggra Mrvyr haq anpu qre qevggra Mrvyr qra Vaunyg iba z nhftrora.

(5) Betrachten Sie die dritte Zeile des unten stehenden Codes: Hat sich durch die Änderung des Arrays `p` der Inhalt von `q` geändert? Falls ja, warum? Falls nein, warum hat es sich nicht geändert?
Nein, weil hier auf Advanced Indexing zurückgegriffen wird und hierbei Kopien und keine Views erstellt werden.

In [5]:
p = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
q = p[[1, 2], 0]
print(m)
p[1, 0] = 25
print(m)

[[10  3]
 [ 6  7]]
[[10  3]
 [ 6  7]]


**Antwort (rot-13 kodiert):** Arva, qre Vaunyg iba d äaqreg fvpu qnqhepu avpug. Orv Nqinaprq Vaqrkvat jreqra vzzre Xbcvra qre Neenlf remrhtg. Yrqvtyvpu orvz Onfvp Vaqrkvat, qnf fvr va rvarz qre ibenatrtnatrara Pbqrorvfcvryr xraaratryreag unggra, jreqra yrqvtyvpu "Ivrjf" haq xrvar Xbcvra remrhtg.

## 2 Broadcasting - Teil 1

Broadcasting ist eine der häufigsten Fehlerquellen, die Sie nur verstehen können, wenn Sie sich mit den sogenannten Broadcasting-Regeln von Numpy beschäftigt haben. Diese Regeln legen fest, wie Numpy Arrays miteinander verrechnet werden können - und diese Regeln unterscheiden sich in Teilen von den Rechenregeln, die Sie aus der linearen Algebra kennen.

- Lesen Sie jetzt [diesen Buchabschnitt](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html) und verstehen Sie die drei Broadcasting-Regeln.

Unten sehen Sie eine Operation mit zwei Numpy Arrays `a` und `b`.

**Ihre Aufgaben**

(1) Betrachten Sie die unten stehende Code-Zelle. Welchen Shape (Anzahl Zeilen, Anzahl Spalten) wird das Numpy Array `c` erhalten? 

  * Tragen Sie ihre Voraussage in die Variable `shape` ein. 
  * Begründen Sie Ihre Vorhersage mit den drei Broadcasting Regeln aus dem Buch.
  * Berechnen Sie auf Papier das zu erwartende Ergebnis. Tragen Sie es als Numpy Array in die Variable `ergebnis` ein.
  * Führen Sie dann jeweils die Zelle aus, um zu schauen, ob Sie richtig lagen.

In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b

# Ihre Vorhersagen
shape = (3,)
ergebnis = np.array([5,7,9])

print('{}\n'.format('Shape korrekt.' if np.all(shape==c.shape) else 'Shape nicht korrekt.'))
print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(ergebnis, c) else 'Ergebnis nicht korrekt.'))

Shape korrekt.

Ergebnis korrekt.



(2) Betrachten Sie die unten stehende Code-Zelle. Welchen Shape (Anzahl Zeilen, Anzahl Spalten) wird das Numpy Array `c` erhalten? 

  * Tragen Sie ihre Voraussage in die Variable `shape` ein. 
  * Begründen Sie Ihre Vorhersage mit den drei Broadcasting Regeln aus dem Buch.
  * Berechnen Sie auf Papier das zu erwartende Ergebnis. Tragen Sie es als Numpy Array in die Variable `ergebnis` ein.
  * Führen Sie dann jeweils die Zelle aus, um zu schauen, ob Sie richtig lagen.

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])[:, np.newaxis]

c = a + b

shape = (3, 3) # Ihre Vorhersage
ergebnis = np.array([[5,6,7],[6,7,8],[7,8,9]])

print('{}\n'.format('Shape Korrekt.' if np.all(shape==c.shape) else 'Shape nicht korrekt.'))
print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(ergebnis, c) else 'Ergebnis nicht korrekt.'))

Shape Korrekt.

Ergebnis korrekt.



(3) Betrachten Sie die unten stehende Code-Zelle. Welchen Shape (Anzahl Zeilen, Anzahl Spalten) wird das Numpy Array `c` erhalten? 

  * Tragen Sie ihre Voraussage in die Variable `shape` ein. 
  * Begründen Sie Ihre Vorhersage mit den drei Broadcasting Regeln aus dem Buch.
  * Berechnen Sie auf Papier das zu erwartende Ergebnis. Tragen Sie es als Numpy Array in die Variable `ergebnis` ein.
  * Führen Sie dann jeweils die Zelle aus, um zu schauen, ob Sie richtig lagen.

In [8]:
a = np.array([[1, 0, 0], [0, 0, 2]])
b = np.ones(12).reshape((4, 1, 3))
# print(a)
# Zuerst wird das Array a nach Regel 1 mit einer Dimension links befüllt, weil b eine Dimension mehr hat
# print(a.reshape((1,2,3)))
# Anschließend werden nach Regel 2 bei unterschiedlichen Werten bei einer Dimension, das Array dessen Dimension 1 ist, erweitert, bis die Dimensionen gleich sind.
# print(b)
c = a * b

shape = (4,2,3) # Ihre Vorhersage
ergebnis = np.array([[[1,0,0],[0,0,2]], [[1,0,0],[0,0,2]], [[1,0,0],[0,0,2]],[[1,0,0],[0,0,2]]]) # Ich vermute, dass sie hierüber länger nachdenken werden.

print('{}\n'.format('Shape korrekt.' if np.all(shape==c.shape) else 'Shape nicht korrekt.'))
print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(ergebnis, c) else 'Ergebnis nicht korrekt.'))

Shape korrekt.

Ergebnis korrekt.



## 3 Broadcasting Teil 2

Ein häufiger Vorverarbeitungsschritt, der Ihnen in verschiedenen Data Science Projekten begegnen wird, ist die Normierung von Daten. Häufig werden dabei Datensätze, z.B. Zeitreihen, auf Mittelwert $0$ und Standardabweichung $1$ normiert. Dieser Vorgang wird auch *z-scoring* (oder: *Standardisierung*) genannt:

Sei $x_i$ der $i$-te Datenpunkt einer Zeitreihe. Dann ist der z-score dieses Datenpunkts definiert als

$$\tilde{x}_i = \frac{x_i - \bar{x}}{\sigma},$$ 

wobei $\bar{x}$ den Mittelwert sowie $\sigma$ die Standardabweichung der Zeitreihe bezeichnen.

Das in der unten stehenden Code-Zelle definierte Numpy Array `X` enthält 5 Zeitreihen (Spalten) mit je 30 Einträgen (Zeilen). 

* Nutzen Sie Broadcasting sowie [np.mean](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html) und [np.std](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html), um die Zeitreihen auf Mittelwert 0 und Varianz 1 zu normieren. Die transformierten Zeitreihen sollen im Numpy Array `Y` gespeichert werden. Dabei schreiben Sie nur eine Zeile Code, um die Zeitreihen zu transformieren.
* Beachten Sie das `axis` Argument bei `np.mean` und `np.std`.

In [9]:
import numpy as np
np.random.seed(0)
X = np.random.random((30, 5))
#print(X[0])
#print(np.std(X, axis=1))
#print(np.mean(X, axis=1))
#print("X")
#print(X)
#print(X-np.mean(X, axis=1))

# Ihr Ergebnis: Y =
Y = (X-np.mean(X, axis=0))/np.std(X, axis=0)
print(Y)
print(np.mean(Y))
print(np.std(Y))

[[ 0.16740311  0.99146058  0.26566035 -0.19189575 -0.10401878]
 [ 0.55391341 -0.15048406  1.19070719  1.37326414 -0.23972755]
 [ 1.13451499  0.22511946  0.15453418  1.23099463 -1.29401013]
 [-1.67071577 -1.86737303  1.00137287  0.67994818  1.40231461]
 [ 1.8785996   1.33687639 -0.18655411  0.68881496 -1.13459362]
 [ 0.53013254 -1.36084517  1.36001366 -0.27798696 -0.13436721]
 [-0.96432242  1.23434539 -0.20361099 -0.10387638 -1.47032689]
 [ 0.44140643  0.56737441  0.31101693  1.29883439  0.76721883]
 [-0.58628567 -0.15276817  0.56930829 -2.00327065  0.71641712]
 [ 0.65242656 -1.08511345 -1.25097251 -1.04946742 -0.30631341]
 [ 0.25253703 -0.14631163  1.49990208 -1.84697374 -0.82883566]
 [-1.37537957  0.73608391 -0.85291057 -0.48555474 -0.7088681 ]
 [-1.38469563 -1.49650412  0.43711227 -1.71190993 -0.87032586]
 [-0.54958864  1.42669551 -1.35283637  0.90340231 -1.20943159]
 [ 1.87000439 -0.02269919  1.4627326   0.03220936  0.96107412]
 [-1.86158691 -0.78718832 -1.2789142  -1.12155557 -1.13

## 4 Advanced Indexing

Advanced Indexing, auch manchmal *fancy indexing* genannt, erlaubt Ihnen auf schnelle Art und Weise komplexe Zugriffe auf Arrays zu realisieren.

- Lesen Sie jetzt [diesen Buchabschnitt](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html) und verstehen Sie fancy indexing.

**Ihre Aufgaben**

(1) Betrachten Sie die unten stehenden Code-Zellen.
* Tragen Sie in der Variable `vorhersage` ein, welches Array Sie in Variable `y` erwarten.
* Prüfen Sie durch Ausführen des Codes, ob Ihre Vorhersage richtig war.
* Beantworten Sie die Frage: Wodurch wird der Shape des Arrays `y` bestimmt?

In [10]:
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]]
# Der Shape von y wird durch die eckigen Klammern hinter dem x bestimmt. Die beiden Arrays [0,1,2] (Zeile) und [0,1,0] sind die Zeilen und Spalten der Werte aus x, die in y geschrieben werden sollen. Da es sich um drei Arraywerte ([0,0],[1,1],[2,0]) handelt, hat das Array eine Shape von (3,).

vorhersage = np.array([1,4,5]) # Ihre Vorhersage

print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(vorhersage, y) else 'Ergebnis nicht korrekt.'))

Ergebnis korrekt.



(2) Betrachten Sie den unten stehenden Code-Zellen.
* Tragen Sie in der Variable `vorhersage` ein, welches Array Sie in Variable `y` erwarten.
* Prüfen Sie durch Ausführen des Codes, ob Ihre Vorhersage richtig war.
* Beantworten Sie die Frage: Wodurch wird der Shape des Arrays `y` bestimmt?

In [11]:
x = np.array([[0,  1,  2], [3,  4,  5], [6,  7,  8], [9, 10, 11]]) 
   
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols]
# Die Shape wird ebenso wie bei (1) von den rows und cols bestimmt.

vorhersage = np.array([[0,2],[9,11]]) # Ihre Vorhersage

print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(vorhersage, y) else 'Ergebnis nicht korrekt.'))

Ergebnis korrekt.



(3) Betrachten Sie den unten stehenden Code-Zellen.
* Tragen Sie in der Variable `vorhersage` ein, welches Array Sie in Variable `y` erwarten.
* Prüfen Sie durch Ausführen des Codes, ob Ihre Vorhersage richtig war.
* Beantworten Sie die Frage: Wodurch wird der Shape des Arrays `y` bestimmt?

In [12]:
x = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8],[9, 10, 11]]) 

y = x[1:4,[1,2]] # Kombination von Slicing und Advanced Indexing
# Durch das Slicing wird angegeben, welche Zeilen (die zweite, dritte und vierte Zeile([1,2,3])) in y stehen und durch das Advanced Indexing wird der Spalteninhalt (das zweite und dritte Element) bestimmt.
vorhersage = np.array([[4,5],[7,8],[10,11]]) # Ihre Vorhersage

print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(vorhersage, y) else 'Ergebnis nicht korrekt.'))

Ergebnis korrekt.



Ich darf Ihnen gratulieren. Sie haben hiermit diesen Teil Ihrer Vorbereitungen erfolgreich beendet.

### Lernressourcen

Ich habe Ihnen in der ILIAS "Python Lerngruppe" viele Materialien zum Nachschlagen und Ihr Selbststudium hinterlegt. Sie finden aber natürlich auch im Netz weitere hilfreiche Tutorials:

1. Eine Fülle von Tutorials zum Erlernen von *Python* finden Sie [hier](https://wiki.python.org/moin/BeginnersGuide/Programmers). Es gibt auch eine ganze Reihe von Cheatsheets, zum Beispiel [dieses hier](https://s3.amazonaws.com/dq-blog-files/python-cheat-sheet-basic.pdf).
2. Wenn Sie Programmiererfahrung in Java, aber nicht in Python haben, dann könnten folgender [Vergleich](http://math-cs.gordon.edu/courses/cps122/handouts-2014/From%20Python%20to%20Java%20Lecture/A%20Comparison%20of%20the%20Syntax%20of%20Python%20and%20Java.pdf) sowie die Anleitung [Python for Java Programmers](http://python4java.necaiseweb.org/Main/TableOfContents) hilfreich sein.
3. Wenn Sie Programmiererfahrung in Matlab, aber nicht in Python haben, dann könnte folgende [Webseite](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html) für Sie sehr hilfreich sein. Nutzen Sie daneben auch dieses [Cheatsheet](http://mathesaurus.sourceforge.net/matlab-python-xref.pdf).
4. Ein Tutorial für eine Einführung zu *numpy* finden Sie beispielsweise [hier](https://docs.scipy.org/doc/numpy/user/quickstart.html) oder [hier](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/IntroducingTheNDarray.html).
5. Ein Tutorial, das Ihnen die wichtigste Plotting-Funktion von *Matplotlib* näher bringt, finden Sie beispielsweise [hier](https://matplotlib.org/tutorials/introductory/pyplot.html#sphx-glr-tutorials-introductory-pyplot-py).

